# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nginx-pv-volume
#   labels:
#     type: local
#     app: nginx
# spec:
#   storageClassName: ntnx-retain-sc
#   capacity:
#     storage: 2Gi
#   volumeMode: Filesystem
#   persistentVolumeReclaimPolicy: Retain
#   accessModes:
#     - ReadWriteOnce
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim2
  labels:
    app: nginx
    type: local
spec:
  storageClassName: ntnx-retain-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
