apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim2
  labels:
    app: nginx
    type: local
spec:
  storageClassName: ntnx-retain-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginxdeployment
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 30010
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: StatefulSet
metadata:
  name: nginxdeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxcontainer
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html/test
            subPath: test
            name: nginx-pv
      volumes:
      - name: nginx-pv
        persistentVolumeClaim:
          claimName: nginx-pv-claim2
#    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"