apiVersion: v1
kind: Service
metadata:
  name: {{ include "mynginx.fullname" . }}
  labels:
    {{- include "mynginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "mynginx.selectorLabels" . | nindent 4 }}
